server:
  port: 80
spring:
  #  hibernate:
  #    enable_lazy_load_no_trans: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rest_api_jwt
    password: 1227
    username: postgres
  #    xayr h2
  #    driver-class-name: org.h2.Driver
  #    url: jdbc:h2:mem:restdb
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: never
  main:
    lazy-initialization: true
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
jwt:
  secretKey: SupperKey
  expireTime: 864000000