server:
  port: 80
spring:
  #  hibernate:
  #    enable_lazy_load_no_trans: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rest_api_jwt
    password: 1227
    username: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  main:
    lazy-initialization: true
  mvc:
    servlet:
      path: /api
  jackson:
    date-format: yyyy-MM-dd
jwt:
  secretKey: SupperKey
  expireTime: 864000000
